### PR TITLE
Headphones update

### PR DESCRIPTION
**Pull request by errorslol**

### CODE REVIEW

**Comment by DJ-Laser** [comment]
Nice! Cant wait to see the finished textures! :)

**Comment by errorslol** [comment]
this tidies up and removes all the colors that do not have a dye

**Comment by DJ-Laser** [comment]
Looks great but can you replace all spaces in the name with underscores

**Comment by errorslol** [comment]
Is there anything you would want me to do? I will probably create a concept art folder if that's okay with you.

**Review by DJ-Laser — APPROVED** [review]
yes i will merge thx fot the help

**Pull request merged**
